### ISSUE TITLE
Styles not applied when using TouchableHighlight from 'react-native-gesture-handler'

### ISSUE THREAD

**Issue by emroot** [Temzasse/stitches-native#30] opened 2022-10-12 22:50 UTC
Hey there,

I'm using `react-native-reanimated` and `react-native-gesture-handler` to create some animations.
When using TouchableHighlight (not as string) from `react-native-gesture-handler`, the styles don't get applied, however when I use `TouchableOpacity` as a string, it works fine.

Try this:
``` typescript
import { styled } from '@styled/index';
import { View } from 'react-native';
import { TouchableHighlight } from 'react-native-gesture-handler';
const Container = styled('View', {
  flex: 1,
});
const Touchable = styled('TouchableHighlight', {
  flex: 1,
  backgroundColor: 'red',
});
// styles don't get applied to Touchable2
const Touchable2 = styled(TouchableHighlight, {
  // from react-native-gesture-handler
  flex: 1,
  backgroundColor: 'yellow',
});

export default function Test() {
  return (
    <Container>
      <Touchable>
        <View />
      </Touchable>
      <Touchable2>
        <View />
      </Touchable2>
    </Container>
  );
}

```

**Comment by Temzasse** [comment] 2022-11-02 13:59
Hi @emroot 👋🏻 

Unfortunately I'm not able to reproduce this issue.

Can you provide a Github repo with a reproducible example?

**Comment by Temzasse** [comment] 2022-11-15 12:25
Closing this for not being able to reproduce the issue.

**Closed as completed by Temzasse** 2022-11-15 12:25 UTC
